export const dsKhoa = [
    'Khoa nội tổng quát',
    'Khoa ngoại tổng quát',
    'Khoa sản',
    'Khoa nhi',
    'Khoa cấp cứu',
    'Khoa hồi sức cấp cứu',
    'Khoa xét nghiệm',
    'Khoa chẩn đoán hình ảnh',
    'Khoa gây mê hồi sức',
    'Khoa da liễu',
    'Khoa răng hàm mặt',
    'Khoa mắt',
    'Khoa tai mũi họng',
    'Khoa nội tiết',
    'Khoa tim mạch',
    'Khoa thận - tiết niệu',
    'Khoa hô hấp',
    'Khoa tâm lý',
    'Khoa vật lý trị liệu',
    'Khoa phục hồi chức năng',
    'Khoa dinh dưỡng',
    'Khoa y học cổ truyền',
    'Khoa ung bướu',
    'Khoa huyết học - truyền máu',
    'Khoa sinh lý bệnh',
    'Khoa y học thể thao',
    'Khoa y học gia đình',
    'Khoa sức khỏe cộng đồng',
    'Khoa y học dự phòng',
    'Khoa y học lao động',
    'Khoa di truyền',
    'Khoa dị ứng - miễn dịch lâm sàng'
];
